DECLARE
  v NUMBER;
BEGIN
  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='REGION';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE region (id_region NUMBER(4) NOT NULL, nom_region VARCHAR2(255) NOT NULL, CONSTRAINT region_pk PRIMARY KEY (id_region))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='COMUNA';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE comuna (id_comuna NUMBER(4) NOT NULL, nom_comuna VARCHAR2(100) NOT NULL, cod_region NUMBER(4) NOT NULL, CONSTRAINT comuna_pk PRIMARY KEY (id_comuna), CONSTRAINT comuna_fk_region FOREIGN KEY (cod_region) REFERENCES region(id_region))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='MEDIO_PAGO';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE medio_pago (id_mpago NUMBER(3) NOT NULL, nombre_mpago VARCHAR2(50) NOT NULL, CONSTRAINT medio_pago_pk PRIMARY KEY (id_mpago))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='AFP';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE afp (id_afp NUMBER(5) GENERATED BY DEFAULT AS IDENTITY (START WITH 210 INCREMENT BY 6) NOT NULL, nom_afp VARCHAR2(255) NOT NULL, CONSTRAINT afp_pk PRIMARY KEY (id_afp))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='SALUD';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE salud (id_salud NUMBER(5) NOT NULL, nom_salud VARCHAR2(40) NOT NULL, CONSTRAINT salud_pk PRIMARY KEY (id_salud))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='PROVEEDOR';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE proveedor (id_proveedor NUMBER(5) NOT NULL, nombre_proveedor VARCHAR2(150) NOT NULL, rut_proveedor VARCHAR2(10) NOT NULL, telefono VARCHAR2(20), email VARCHAR2(200), direccion VARCHAR2(200), cod_comuna NUMBER(4) NOT NULL, CONSTRAINT proveedor_pk PRIMARY KEY (id_proveedor), CONSTRAINT proveedor_fk_comuna FOREIGN KEY (cod_comuna) REFERENCES comuna(id_comuna))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='CATEGORIA';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE categoria (id_categoria NUMBER(3) NOT NULL, nombre_categoria VARCHAR2(255) NOT NULL, CONSTRAINT categoria_pk PRIMARY KEY (id_categoria))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='MARCA';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE marca (id_marca NUMBER(3) NOT NULL, nombre_marca VARCHAR2(25) NOT NULL, CONSTRAINT marca_pk PRIMARY KEY (id_marca))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='EMPLEADO';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE empleado (id_empleado NUMBER(4) NOT NULL, rut_empleado VARCHAR2(10) NOT NULL, nombre_empleado VARCHAR2(25) NOT NULL, apellido_paterno VARCHAR2(25) NOT NULL, apellido_materno VARCHAR2(25) NOT NULL, fecha_contratacion DATE NOT NULL, sueldo_base NUMBER(10) NOT NULL, bono_jefatura NUMBER(10), activo CHAR(1) NOT NULL, tipo_empleado VARCHAR2(25) NOT NULL, cod_empleado NUMBER(4), cod_salud NUMBER(5) NOT NULL, cod_afp NUMBER(5) NOT NULL, CONSTRAINT empleado_pk PRIMARY KEY (id_empleado), CONSTRAINT empleado_fk_salud FOREIGN KEY (cod_salud) REFERENCES salud(id_salud), CONSTRAINT empleado_fk_afp FOREIGN KEY (cod_afp) REFERENCES afp(id_afp), CONSTRAINT empleado_fk_empleado FOREIGN KEY (cod_empleado) REFERENCES empleado(id_empleado), CONSTRAINT empleado_ck_activo CHECK (activo IN (''S'',''N'')))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='ADMINISTRATIVO';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE administrativo (id_empleado NUMBER(4) NOT NULL, CONSTRAINT administrativo_pk PRIMARY KEY (id_empleado), CONSTRAINT admin_fk_empleado FOREIGN KEY (id_empleado) REFERENCES empleado(id_empleado))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='VENDEDOR';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE vendedor (id_empleado NUMBER(4) NOT NULL, comision_venta NUMBER(5,2), CONSTRAINT vendedor_pk PRIMARY KEY (id_empleado), CONSTRAINT vendedor_fk_empleado FOREIGN KEY (id_empleado) REFERENCES empleado(id_empleado))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='PRODUCTO';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE producto (id_producto NUMBER(4) NOT NULL, nombre_producto VARCHAR2(100) NOT NULL, precio_unitario NUMBER(8,2) NOT NULL, origen_nacional CHAR(1) NOT NULL, stock_minimo NUMBER(3) NOT NULL, activo CHAR(1) NOT NULL, cod_marca NUMBER(3) NOT NULL, cod_categoria NUMBER(3) NOT NULL, cod_proveedor NUMBER(5) NOT NULL, CONSTRAINT producto_pk PRIMARY KEY (id_producto), CONSTRAINT producto_fk_marca FOREIGN KEY (cod_marca) REFERENCES marca(id_marca), CONSTRAINT producto_fk_categoria FOREIGN KEY (cod_categoria) REFERENCES categoria(id_categoria), CONSTRAINT producto_fk_proveedor FOREIGN KEY (cod_proveedor) REFERENCES proveedor(id_proveedor), CONSTRAINT producto_ck_activo CHECK (activo IN (''S'',''N'')), CONSTRAINT producto_ck_origen CHECK (origen_nacional IN (''S'',''N'')))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='VENTA';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE venta (id_venta NUMBER(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 5050 INCREMENT BY 3) NOT NULL, fecha_venta DATE NOT NULL, total_venta NUMBER(10) NOT NULL, cod_mpago NUMBER(3) NOT NULL, cod_empleado NUMBER(4) NOT NULL, CONSTRAINT venta_pk PRIMARY KEY (id_venta), CONSTRAINT venta_fk_medio_pago FOREIGN KEY (cod_mpago) REFERENCES medio_pago(id_mpago), CONSTRAINT venta_fk_empleado FOREIGN KEY (cod_empleado) REFERENCES empleado(id_empleado))';
  END IF;

  SELECT COUNT(*) INTO v FROM user_tables WHERE table_name='DETALLE_VENTA';
  IF v=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE detalle_venta (cod_venta NUMBER(4) NOT NULL, cod_producto NUMBER(4) NOT NULL, cantidad NUMBER(3) NOT NULL, CONSTRAINT detalle_venta_pk PRIMARY KEY (cod_venta, cod_producto), CONSTRAINT det_venta_fk_venta FOREIGN KEY (cod_venta) REFERENCES venta(id_venta), CONSTRAINT det_venta_fk_producto FOREIGN KEY (cod_producto) REFERENCES producto(id_producto))';
  END IF;
END;
/
